(ns subspace.basis.inner-product-types);

(def LEFT_CONTRACTION  1)
(def RIGHT_CONTRACTION  2)
(def HESTENES_INNER_PRODUCT 3)
(def MODIFIED_HESTENES_INNER_PRODUCT 4)

(def LC LEFT_CONTRACTION)
(def RC RIGHT_CONTRACTION)
(def HIP HESTENES_INNER_PRODUCT)
(def MHIP MODIFIED_HESTENES_INNER_PRODUCT)
